yatube/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.index, name= 'index'),
    path('group/<slug:slug>/', views.group_posts, name='posts_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='post')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, 
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts_list'
    )


class Meta:
    ordering = ['-pub_date']

# Create your models here.

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    title = ' Последнее обновление на сайте '
    template = 'posts/index.html'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, template, context )


def group_posts(request, slug):     
    group = get_object_or_404(Group, slug=slug )
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)
# Create your views here.

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    <meta charset="utf-8">  <!-- Кодировка сайта --> 
    <meta name="viewport" content='width-device-width, initial-scale=1'> <!-- Сайт готов работать с мобильныз устройств -->
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <title>{{ title }}</title>    
  </head>
  <body>       
    {% include 'includes/header.html' %}

    {% block title %}
    {% endblock title %}

    {% block content %}
    {% endblock %}

    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
{% load static %}
<footer>
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<!--templates/header.html-->
<!-- Использованы классы бустрап для создания типовой навигации с логотипом-->
      <!-- В дальнейшем здесь будет создано полноценное меню-->
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container"
      <a class="navbar-brand" href="{% url 'posts:posts_list' slug='list' %}">
        <img src="{% static 'img/logo.png'%}" width="30" class="d-inline-block align-top alt">
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="container py-5">
    <h1>Лев Толстой – зеркало русской революции.</h1>
      {% for post in posts %}
      <p>
        Группа {{ post.group.get_full_name }}
      </p>
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y"}}
          </li>
        </ul>      
        <p>{{ post.text }}</p>        
      </article>
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  </div>
</main>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
{% block content %}
<div class="container py-5">     
  <h1>{{ text }}</h1>
  {% for post in posts %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>      
    <p>{{ post.text }}</p>
    {% if post.group %}
      <a href="{% url 'post:posts_list'  slug='list' %}">все записи группы</a>
    {% endif %}
  </article>
  <hr>
  <article>
    <ul>
      <li>
        Автор: Лев Толстой
      </li>
      <li>
        Дата публикации: 29 июля 1854
      </li>
    </ul> 
    <p>
      Исправленіе мое идетъ прекрасно. Я чувствую, какъ отношенія мои становятся пріятны и легки 
      съ людьми всякаго рода, съ тѣхъ поръ какъ я рѣшился быть скромнымъ и убѣдился въ томъ, 
      что казаться всегда величественнымъ и непогрѣшнымъ вовсе не есть необходимость. Я очень 
      веселъ. И дай Богъ, какъ мнѣ кажется, — чтобы веселье это происходило отъ самаго меня; 
      отъ желаній всѣмъ быть пріятнымъ, скромности, необидчивости и внимательности за вспышками. 
      — Тогда бы я всегда былъ веселъ и почти всегда счастливъ. 
      Утромъ рѣшилъ было сидѣть дома, позаниматься, но дѣло не пошло и не утерпѣлъ вечеромъ, 
      чтобы не пойдти пошляться. Идя отъ ужина, мы съ Тишк[евичемъ] остановились у бардели и насъ 
      накрылъ Крыжановскій, что, признаюсь, было мнѣ не совсѣмъ пріятно. Упрекаю себя за 
      безхарактерность, что не высидѣлъ дома, и зa праздность цѣлаго дня. Это главный пунктъ. (2)
    </p>
    {% if post.group %}
      <a href="{% url 'post:posts_list' slug='list' %}">все записи группы</a>
    {% endif %}
  </article>
  <hr>
  <article>
    <ul>
      <li>
        Автор: Лев Толстой
      </li>
      <li>
        Дата публикации: 28 июля 1854
      </li>
    </ul> 
    <p>
      Пишу въ самомъ пріятномъ веселомъ расположеніи духа, въ которомъ я провелъ весь вечеръ. 
      Утро читалъ, объѣдался грушами и вмѣсто обѣда ѣлъ сыръ. Несмотря на кутежи у Сталыпина и 
      Сержпутовскаго по случаю полученія наградъ, не завидовалъ, а провелъ день весело. Вечеромъ 
      хватилъ босонож[ку] и выпилъ бокала два шампанскаго съ Шварц[емъ], Вейлеровскимъ [?] и 
      Гембичомъ, потомъ болталъ съ Шубинымъ и съ Сашей Горчаковымъ. — Исключая праздности, 
      днемъ своимъ очень доволенъ. (1)
    </p>
    {% if post.group %}
      <a href="{% url 'post:posts_list' slug='list' %}">все записи группы</a>
    {% endif %}
  </article>
        <!-- под последним постом нет линии -->
{% endfor%}
</div>
{% endblock %}
 
    